# Generated by Django 5.2 on 2025-04-21 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('installation_date', models.DateField()),
                ('last_service_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('filter_change', 'Filter Change'), ('coil_cleaning', 'Coil Cleaning'), ('refrigerant_check', 'Refrigerant Check'), ('thermostat_calibration', 'Thermostat Calibration'), ('ductwork_inspection', 'Ductwork Inspection')], max_length=50)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('last_performed', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=100)),
                ('completion_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('issue_found', 'Issue Found')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='maintenance_images/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancetask')),
            ],
        ),
    ]
